const frases = {
    triste: [
        "Estoy aquí para abrazarte en los días grises.",
        "No estás sola, amor, siempre estaré a tu lado.",
        "Es normal sentirse triste a veces, y aquí estoy para ti.",
        "Eres fuerte, y juntos superaremos cualquier tristeza.",
        "Permíteme ser tu refugio en estos momentos difíciles.",
        "Puedes llorar si lo necesitas, yo estaré aquí para ti.",
        "La tristeza es temporal, pero mi amor por ti es eterno.",
        "Estoy aquí para ti, incluso en los días más oscuros.",
        "Vamos a superar esto juntos, te lo prometo.",
        "Tu dolor es mi dolor, y no dejaré que enfrentes esto sola.",
        "Siempre puedes contar conmigo, amor.",
        "Te amo, incluso en tus momentos más tristes.",
        "No dejes que la tristeza te gane, aquí estoy yo.",
        "Me duele verte triste, pero estaré aquí para apoyarte.",
        "Juntos podemos con todo, incluso con la tristeza.",
        "Eres más fuerte de lo que crees, y estoy aquí para recordártelo.",
        "Cuando estés lista, hablemos, amor.",
        "Mi amor por ti es más grande que cualquier tristeza.",
        "Te amo, y juntos superaremos esta tristeza.",
        "Siempre encontrarás consuelo en mis brazos.",
        "¿Si te hago el amor se te quita? ❤️‍🔥",
        "Amor, lamento que estés pasando por esto. Estoy aquí para ti, en cada paso del camino.",
        "Tu tristeza me duele, pero juntos podemos encontrar consuelo y esperanza.",
        "No tienes que enfrentar esto sola, cuenta conmigo para lo que necesites.",
        "Eres mi todo, y quiero que sepas que siempre estaré a tu lado, sin importar lo que pase.",
        "En los momentos difíciles, quiero ser la razón por la que sonríes nuevamente.",
        "Quiero que sepas que tu tristeza es importante para mí, y estoy aquí para escucharte y apoyarte.",
        "Cuando sientas que el mundo te pesa, recuerda que mi amor es un refugio seguro para ti.",
        "Aunque ahora sea difícil, confía en que juntos podemos superar cualquier obstáculo.",
        "Tu dolor es real, y mi amor por ti es aún más profundo en estos momentos.",
        "Permíteme ser la persona que te haga sentir mejor, incluso en los días más oscuros.",
        "Eres fuerte y valiente, y estoy aquí para recordártelo cuando más lo necesites.",
        "Cada lágrima que derramas es un recordatorio de lo mucho que te amo y me importas.",
        "No importa cuán difícil sea el día, mi amor por ti nunca cambiará.",
        "Estoy aquí para abrazarte, consolarte y hacerte sentir que todo estará bien.",
        "Permíteme ser tu luz en los momentos de oscuridad, para que nunca te sientas sola.",
        "Tu tristeza es temporal, pero mi amor por ti es eterno y siempre estará aquí para ti.",
        "Déjame ayudarte a llevar esta carga, para que te sientas un poco más ligera.",
        "Eres una persona increíble, y aunque ahora sea difícil, tu fortaleza siempre brillará.",
        "No importa cuán grande sea el desafío, estaré contigo para enfrentarlo juntos.",
        "Tu felicidad significa todo para mí, y haré todo lo posible para verte sonreír de nuevo.",
    ],
    enojada: [
        "Sé que estás molesta, pero estoy aquí para escucharte.",
        "Respira, amor, vamos a resolverlo juntos.",
        "Tu enojo no cambia lo mucho que te amo.",
        "Hablemos cuando estés lista, te amo.",
        "Estoy aquí para apoyarte, incluso cuando estás enojada.",
        "Es normal sentirse enojada a veces, y estoy contigo.",
        "Vamos a encontrar una solución juntos, amor.",
        "Puedes contar conmigo, incluso en los días difíciles.",
        "Te amo, incluso cuando estás enfadada.",
        "Estoy aquí para ayudarte a calmarte.",
        "Eres importante para mí, y quiero que te sientas mejor.",
        "Vamos a superar esto juntos.",
        "Siempre podemos hablar y resolverlo.",
        "Te amo, sin importar cuán enojado estés.",
        "Tu bienestar es lo más importante para mí.",
        "No dejes que el enojo nos separe, amor.",
        "Estoy aquí para ti, en todo momento.",
        "Quiero que estés bien, amor.",
        "Te amo más de lo que las palabras pueden expresar.",
        "Hablemos y encontremos una solución juntos.",
        "Hasta Enojada te vez preciosa.",
        "¿Si te hago el amor se te quita? ❤️‍🔥",
        "Cuando el mundo te ponga a prueba, quiero que sepas que siempre tendrás mi apoyo.",
        "No importa cuán difícil sea la situación, enfrentémosla juntos y saldremos adelante.",
        "Tu enojo es válido, y estoy aquí para escucharte y ayudarte a superar esto.",
        "Déjame ser el consuelo que necesitas cuando el mundo parece estar en tu contra.",
        "Aunque las cosas no salgan como esperabas, siempre puedes contar con mi amor y apoyo.",
        "Eres fuerte y valiente, y juntos podemos enfrentar cualquier desafío que se nos presente.",
        "No dejes que las dificultades te definan, porque eres mucho más que las situaciones que enfrentas.",
        "Estoy aquí para ayudarte a canalizar esa frustración en algo positivo y constructivo.",
        "Quiero ser tu lugar seguro, donde puedas desahogar tus sentimientos sin miedo ni juicio.",
        "Cuando todo parezca oscuro, recuerda que mi amor es una luz constante en tu vida.",
        "No importa cuán complicado sea el problema, enfrentémoslo con la certeza de que juntos podemos superarlo.",
        "Tu fortaleza es admirable, y estoy aquí para recordarte que eres capaz de superar cualquier cosa.",
        "Permíteme ser tu refugio cuando el mundo sea demasiado pesado de llevar.",
        "Quiero ser la voz que te anime cuando sientas que todo está en contra tuya.",
        "A veces, las situaciones difíciles nos enseñan algo valioso. Estoy aquí para aprender y crecer contigo.",
        "Incluso en los momentos más oscuros, quiero que sientas mi amor y apoyo incondicional.",
        "Eres increíblemente fuerte, y mi amor por ti solo crece cuando veo tu determinación.",
        "No dejes que las frustraciones te apaguen, porque tienes una luz interior que ilumina todo a tu alrededor.",
        "Estoy aquí para ti, dispuesto a enfrentar cualquier tormenta junto a ti, porque te amo profundamente.",
    ],
    preocupada: [
        "Estoy aquí para aliviar tus preocupaciones.",
        "Todo estará bien, te lo prometo.",
        "Tienes mi apoyo incondicional, siempre.",
        "Eres más fuerte de lo que crees, confía en ti misma.",
        "No tienes que enfrentar esto sola, estoy contigo.",
        "Tus preocupaciones también son mías, y juntos podemos con ellas.",
        "Respira, amor, estoy aquí para ayudarte.",
        "Vamos a resolver esto juntos, paso a paso.",
        "No estás sola en esto, estoy contigo.",
        "Tienes la fortaleza para superar cualquier obstáculo.",
        "Confío en ti, y sé que saldremos adelante.",
        "No permitas que las preocupaciones te consuman, aquí estoy yo.",
        "Eres mi prioridad, y siempre lo serás.",
        "Te amo, y siempre te apoyaré.",
        "Estoy aquí para hacerte sentir segura.",
        "Todo estará bien, no estás sola.",
        "Juntos superaremos cualquier preocupación.",
        "No dejes que las preocupaciones te ganen, te amo.",
        "Estoy contigo, en cada paso del camino.",
        "Vamos a resolver esto juntos, confía en mí.",
        "¿Si te hago el amor se te quita? ❤️‍🔥"
    ],
    desmotivada: [
        "Eres increíble, y estoy aquí para recordártelo.",
        "No pierdas la fe en ti misma, amor.",
        "Juntos encontraremos la motivación que necesitas.",
        "Confío en ti, y sé que puedes lograrlo.",
        "Estoy aquí para apoyarte, siempre.",
        "No te rindas, tienes mucho potencial.",
        "Te amo, y creo en ti.",
        "Eres capaz de grandes cosas, no lo olvides.",
        "Estoy aquí para ayudarte a levantarte.",
        "No estás sola, estoy contigo en cada paso.",
        "Tienes la fortaleza para superar cualquier desafío.",
        "Estoy aquí para apoyarte en todo momento.",
        "Recuerda que eres valiosa y capaz.",
        "Te amo, y juntos superaremos cualquier obstáculo.",
        "No te rindas, amor, estoy aquí contigo.",
        "Eres mi inspiración, no lo olvides.",
        "Confío en tu capacidad para superar cualquier cosa.",
        "Estoy aquí para ayudarte a encontrar tu motivación.",
        "Juntos podemos lograr todo lo que te propongas.",
        "Eres fuerte, y estoy aquí para recordártelo.",
        "¿Si te hago el amor se te quita? ❤️‍🔥",
        "Amor, en los días difíciles, recuerda que estoy aquí para apoyarte en cada paso.",
        "Eres capaz de lograr grandes cosas, y estoy aquí para recordártelo siempre.",
        "No importa cuán oscura parezca la situación, juntos podemos encontrar la luz.",
        "Eres increíblemente fuerte, y confío en que superarás cualquier obstáculo.",
        "Tu pasión y talento me inspiran todos los días, no olvides lo increíble que eres.",
        "Déjame ser tu impulso cuando sientas que no puedes más.",
        "Estoy aquí para ti, amor, para recordarte lo mucho que vales.",
        "Incluso en los días grises, quiero que sepas que siempre serás mi sol.",
        "Eres mi motivo de alegría, y quiero devolverte esa felicidad en cada momento.",
        "No dejes que la desmotivación te gane, porque tienes un corazón fuerte y valiente.",
        "Siempre estaré aquí para levantarte cuando sientas que no puedes más.",
        "Tu fuerza interior es increíble, y estoy aquí para ayudarte a verla de nuevo.",
        "No importa cuántas veces caigas, siempre estaré aquí para levantarte.",
        "Amor, estó es temporal, y sé que encontrarás de nuevo tu camino.",
        "Eres mi heroína, y quiero ayudarte a redescubrir esa fuerza dentro de ti.",
        "Cuando sientas que no puedes, recuerda que estoy aquí para apoyarte.",
        "Nuestro amor es una fuente de energía infinita, y juntos podemos superar cualquier cosa.",
        "Tienes un alma hermosa y una voluntad inquebrantable, confío en ti.",
        "Eres más fuerte de lo que crees, y estoy aquí para ayudarte a ver eso.",
        "Amor, incluso en los momentos más difíciles, quiero que sepas que siempre estaré a tu lado."
    ],
    aburrida: [
        "¿Qué le dice una iguana a otra iguana? Somos iguanitas. 🦎",
        "¿Por qué los pájaros no usan Facebook? Porque ya tienen Twitter. 🐥",
        "¿Qué hace una abeja en el gimnasio? ¡Zum-ba! 🐝",
        "¿Cuál es el animal más antiguo? La cebra, porque está en blanco y negro. 🦓",
        "¿Cuál es el colmo de Aladdín? Tener mal genio. 🔦",
        "¿Por qué el libro de matemáticas estaba triste? Porque tenía muchos problemas. 📕",
        "¿Qué hace un perro con un taladro? ¡Taladrando! 🐶",
        "¿Cómo se dice pañuelo en japonés? Saka-moko. 🧻",
        "¿Cuál es el colmo de un electricista? No encontrar corriente en el río. 🧑‍🔧",
        "¿Qué le dice una impresora a otra? ¿Ese papel es tuyo o es una impresión mía? 🖨️",
        "¿Por qué el sol nunca va a la universidad? Porque ya tiene un millón de grados. ☀️",
        "¿Qué hace una araña en la computadora? Saca la red. 🕷️",
        "¿Qué le dice un gusano a otro? Voy a dar una vuelta a la manzana. 🪱",
        "¿Qué hace una vaca con los ojos cerrados? Leche concentrada. 🐄",
        "¿Qué le dice un semáforo a otro? No me mires, me estoy cambiando. 🚦",
        "¿Cómo se dice pelo sucio en chino? Chin cham pu. 🛀",
        "¿Cuál es el café más peligroso del mundo? El ex-preso.🔪",
        "¿Cómo se despiden los químicos? Ácido un placer. 🧪",
        "¿Qué le dice un jardinero a otro? ¡Disfrutemos mientras ¡podamos! ✂️",
        "¿Por qué el mar nunca se seca? Porque no tiene toalla. 🌊",
        "¿Qué le dice el número 0 al número 8? ¡Bonito cinturón! 🤣",
        "¿Por qué los elefantes no usan computadoras? Porque les da miedo el ratón. 🐘",
        "¿Qué hace una abeja en la cama? ¡Bzzzzz-zzzz! 🐝",
        "¿Qué le dice un techo a otro? Techo de menos. 🏚️",
        "¿Por qué los esqueletos no juegan al fútbol? Porque les da miedo romperse los huesos. 🦴",
        "¿Qué hace una enfermera cuando está aburrida? ¡Toma el pulso de la situación! 🫀",
        "¿Cuál es el colmo de una enfermera? Tener un mal día y no encontrar cura. 😷",
        "¿Qué hace un enfermero con un libro? ¡Toma su lectura! 📙",
        "¿Qué le dice una venda a otra? ¡Me tienes enrollado! 🤕",
        "¿Si te hago el amor se te quita? ❤️‍🔥",
    ],
    estresada: [
        "Amor, déjame quitarte ese estrés con un abrazo que te haga olvidar el mundo.",
        "Tu sonrisa es mi calma, y quiero devolverte la paz con un beso.",
        "Eres la razón por la que todo tiene sentido, incluso en los días difíciles.",
        "Déjame ser tu refugio, donde el estrés se derrite y solo quedamos tú y yo.",
        "Quiero que todo tu estrés desaparezca entre mis brazos.",
        "No hay problema que no podamos superar juntos, confía en mí.",
        "Cada momento a tu lado es un recordatorio de que lo mejor está por venir.",
        "Dame tu mano, amor, y caminemos juntos lejos de cualquier preocupación.",
        "Quiero que cierres los ojos y pienses solo en lo mucho que te amo.",
        "Eres mi prioridad, y haré lo que sea para verte tranquila y feliz.",
        "Quiero ser la razón por la que te olvidas del mundo, aunque sea por un momento.",
        "Déjame hacerte olvidar todo lo que te preocupa con un beso que dure para siempre.",
        "Cuando estás estresada, solo quiero acariciarte hasta que sientas que el tiempo se detiene.",
        "Nada más importa cuando estoy contigo, así que olvida el estrés y déjate llevar.",
        "Tu cuerpo y el mío juntos pueden hacer que cualquier problema desaparezca.",
        "Eres la mujer más increíble del mundo, y nada debería robarte esa paz.",
        "Quiero ser la razón por la que te sientes tranquila y amada, incluso en los peores días.",
        "Ven, quiero llenarte de besos hasta que no puedas recordar qué era lo que te estresaba.",
        "Quiero dedicarme solo a ti, a hacerte sentir amada y deseada como mereces.",
        "Amor, respira profundo, estoy aquí para apoyarte en todo.",
        "Déjame hacerte olvidar el estrés con un abrazo lleno de amor.",
        "No tienes que cargar con todo sola, estoy aquí para compartir tus preocupaciones.",
        "Tu paz es mi prioridad, haré todo lo posible para ayudarte a sentirte mejor.",
        "Vamos a tomarnos un momento para relajarnos juntos, solo tú y yo.",
        "Eres fuerte, pero no tienes que serlo todo el tiempo. Estoy aquí para ti.",
        "Cuando estés estresada, piensa en lo mucho que te amo y cómo siempre estaré a tu lado.",
        "Tu bienestar es lo más importante para mí, no dudes en apoyarte en mí.",
        "Eres increíble en todo lo que haces, pero no olvides cuidarte también.",
        "Quiero ser tu refugio, el lugar donde puedas relajarte y sentirte en paz.",
        "Déjame cuidar de ti, amor. Mereces un descanso de todo ese estrés.",
        "No importa cuán difícil sea el día, siempre tendrás mi amor para aliviar el peso.",
        "Eres lo más importante para mí, y haré todo lo posible para que te sientas mejor.",
        "Vamos a dejar el estrés atrás y enfocarnos en nosotros, en nuestro amor.",
        "Quiero que sepas que estoy aquí, dispuesto a escuchar y ayudarte a liberar cualquier tensión.",
        "Eres mi todo, y quiero que sientas mi apoyo en cada momento difícil.",
        "No hay nada que no podamos superar juntos, incluso el día más estresante.",
        "Déjame hacerte sentir querida y cuidada, porque te lo mereces más que nadie.",
        "Tu sonrisa es mi mayor recompensa, y haré lo que sea para verla de nuevo.",
        "Amor, confía en que este momento pasará, y mientras tanto, estoy aquí para ti.",
        "¿Si te hago el amor se te quita? ❤️‍🔥",
    ],
    ansiosa: [
        "Amor, cuando estés ansiosa, quiero ser el lugar donde encuentres paz.",
        "Déjame abrazarte tan fuerte que toda tu ansiedad se disuelva.",
        "No tienes que enfrentar esto sola, estoy aquí para ayudarte a respirar más fácil.",
        "Tu ansiedad no me asusta, estoy aquí para amarte aún más.",
        "Cuando sientas que el mundo se desmorona, quiero ser el suelo firme bajo tus pies.",
        "Déjame besarte hasta que cada pensamiento ansioso se desvanezca.",
        "Eres mi todo, y no hay nada que no podamos superar juntos.",
        "Cuando la ansiedad te inunde, quiero ser el puerto seguro donde encuentres calma.",
        "No estás sola en esto, te tengo a ti y tú me tienes a mí.",
        "Tu tranquilidad es mi prioridad, y haré lo que sea para devolvértela.",
        "Quiero que sepas que estoy aquí, listo para hacerte olvidar el mundo con un beso.",
        "Tus ansiedades no cambian lo que siento por ti, solo me hacen querer abrazarte más fuerte.",
        "Déjame llevarte lejos de tus pensamientos, a un lugar donde solo existamos tú y yo.",
        "Tu belleza brilla incluso en los momentos difíciles, y quiero recordártelo siempre.",
        "Quiero ser la razón por la que te sientes segura y amada.",
        "No importa qué tan fuerte sea la ansiedad, mi amor por ti siempre será más fuerte.",
        "Quiero hacerte sentir tan amada que no haya espacio para la ansiedad.",
        "Tus preocupaciones son mis preocupaciones, y juntos las enfrentaremos.",
        "Déjame acariciarte hasta que sientas que la ansiedad no tiene cabida en tu corazón.",
        "Amor, estoy aquí contigo, y siempre lo estaré, pase lo que pase.",
        "Tu tranquilidad es lo más importante para mí, vamos a superarlo juntos.",
        "Eres mi mundo, y haré todo lo posible para que te sientas segura y amada.",
        "No estás sola en esto, siempre tienes mi amor para apoyarte.",
        "Cierra los ojos y siente mi amor rodeándote, todo estará bien.",
        "Cada vez que te sientas ansiosa, recuerda que siempre estaré a tu lado.",
        "Eres mi mayor tesoro, y nada me importa más que tu bienestar.",
        "Déjame ser tu refugio en los momentos difíciles, juntos podemos con todo.",
        "Tu sonrisa es mi sol, y haré lo que sea para devolvértela.",
        "Cuando sientas que el mundo es demasiado, quiero ser tu calma.",
        "Tu paz es mi paz, y haré lo que sea necesario para que te sientas mejor.",
        "No importa cuán oscuro parezca el día, siempre estaré aquí para iluminarlo contigo.",
        "Eres increíblemente fuerte, y estoy aquí para recordártelo cada día.",
        "Déjame tomar tu mano y caminar juntos hacia la tranquilidad.",
        "Nada puede contra nuestro amor, ni siquiera la ansiedad.",
        "Cuando estés ansiosa, quiero que mi abrazo sea tu lugar seguro.",
        "No hay nube tan oscura que nuestro amor no pueda disipar.",
        "Quiero ser tu ancla, para que siempre tengas donde sostenerte.",
        "Todo estará bien, porque lo enfrentaremos juntos, como siempre lo hemos hecho.",
        "Mi amor por ti es más grande que cualquier temor o preocupación.",
    ],
    feliz: [
        "Eres mi alegría en cada día.",
        "Contigo, cada momento es mágico.",
        "Tu felicidad es mi mayor tesoro.",
        "Sonríe, amor, que el mundo se ilumina contigo.",
        "Siempre estaré aquí para celebrar tu alegría.",
        "Verte feliz es mi mejor recompensa.",
        "Mi amor por ti crece con cada sonrisa tuya.",
        "Tu risa es mi melodía favorita.",
        "Gracias por llenar mi vida de color.",
        "Eres la razón por la que sonrío todos los días.",
        "No hay nada más bello que verte sonreír.",
        "Tu felicidad es mi misión de vida.",
        "Cuando estás feliz, el mundo es perfecto.",
        "Tu alegría es contagiosa, amor.",
        "Cada sonrisa tuya me hace amarte más.",
        "Eres mi sol en los días nublados.",
        "Me haces feliz solo con existir.",
        "Tu risa ilumina mi vida.",
        "No hay nada más bonito que verte feliz.",
        "Tu felicidad me hace sentir completo.",
        "¿Estarás más feliz, Si te hago el amor?",
        "¿Si te hago el amor lo estarás más? ❤️‍🔥",
        "Tu sonrisa ilumina mi día, estoy tan feliz de verte tan contenta.",
        "Me encanta verte tan feliz, tu alegría es contagiosa.",
        "Eres una rayito de sol en mi vida, y tu felicidad hace que todo sea aún más brillante.",
        "Cada momento contigo es especial, pero verte feliz lo hace aún mejor.",
        "Tu felicidad es mi felicidad, y no hay nada que desee más que verte siempre así.",
        "Verte tan feliz me recuerda lo afortunado que soy de tenerte en mi vida.",
        "Eres la razón de mi sonrisa, y me encanta verte disfrutar cada momento.",
        "Me haces sentir tan bien cuando estás feliz, eres mi mayor alegría.",
        "Tu felicidad me llena de energía positiva, gracias por compartirla conmigo.",
        "Cada risa tuya es música para mis oídos, y me alegra tanto verte tan contenta.",
        "Tu felicidad es mi mayor recompensa, y siempre haré lo posible por mantenerte así.",
        "Cuando estás feliz, todo parece perfecto. Gracias por hacer mi vida tan maravillosa.",
        "Eres el mejor regalo que he recibido, y verte feliz es todo lo que necesito.",
        "Tu alegría hace que el mundo sea un lugar mejor, y me siento agradecido de estar a tu lado.",
        "Tu felicidad me inspira a ser mejor cada día, y me hace sentir más enamorado que nunca.",
        "Cada sonrisa tuya es un recordatorio de lo increíble que eres y de lo afortunado que soy.",
        "Eres mi fuente de alegría, y ver tu felicidad es el mejor regalo que puedo recibir.",
        "Cuando estás feliz, mi corazón se llena de amor y gratitud por tenerte en mi vida.",
        "Eres mi todo, y verte feliz hace que cada momento sea perfecto.",
        "Verte tan feliz me hace querer hacer todo lo posible para mantener esa sonrisa en tu rostro.",
    ],
    emocionada: [
        "Tu entusiasmo es contagioso, y me alegra ver cómo brillas de emoción.",
        "Me encanta ver cómo te iluminas cuando estás emocionada, es una de las cosas que más amo de ti.",
        "Tu alegría y emoción hacen que todo a tu alrededor sea aún más especial.",
        "Cuando estás emocionada, el mundo entero parece mejor. Estoy tan feliz de compartir estos momentos contigo.",
        "Tu energía positiva y tu entusiasmo me inspiran a disfrutar cada instante aún más.",
        "Verte tan emocionada me hace recordar lo afortunado que soy de tenerte en mi vida.",
        "Tu pasión es contagiosa, y me alegra ver cómo te llena de felicidad.",
        "Cada vez que veo esa chispa en tus ojos, me siento emocionado también.",
        "Tu emoción hace que todo parezca más vibrante y emocionante. Gracias por compartir tu alegría conmigo.",
        "Eres un torbellino de energía positiva, y me encanta estar a tu lado cuando estás así.",
        "Tu entusiasmo es una de las cosas que más admiro de ti, y me encanta ver cómo te llena de vida.",
        "Tu felicidad es mi felicidad, y tu emoción me hace sentir aún más enamorado.",
        "Me haces sentir tan emocionado también, simplemente al verte tan contenta y animada.",
        "Tu entusiasmo es un recordatorio constante de cuán especial eres para mí.",
        "Cada vez que te veo emocionada, mi corazón late más rápido porque comparto tu alegría.",
        "Tu emoción y pasión hacen que cada momento a tu lado sea increíblemente memorable.",
        "Eres la persona más vibrante y animada que conozco, y me encanta ver cómo te iluminas con emoción.",
        "Me llena de felicidad verte tan emocionada, y estoy aquí para disfrutar cada momento contigo.",
        "Tu alegría es contagiosa, y no puedo evitar sonreír cada vez que veo tu entusiasmo.",
        "Tu emoción hace que cada día sea una aventura, y estoy agradecido por cada instante que compartimos.",
        "Tu entusiasmo es una de las cosas que me hace amarte aún más, porque veo lo apasionada que eres por la vida.",
        "Me haces sentir tan emocionado como tú, y no puedo esperar a vivir cada momento contigo.",
        "Cada sonrisa y cada risa tuya cuando estás emocionada hacen que mi corazón se llene de felicidad.",
        "Eres una fuente constante de alegría y emoción, y me encanta estar a tu lado en cada momento.",
        "Tu entusiasmo ilumina incluso los días más oscuros, y me alegra ver cómo te llena de vida.",
        "Cuando estás emocionada, me siento inspirado a disfrutar de la vida con la misma pasión que tú.",
        "Tu alegría es un regalo, y estoy agradecido por cada momento en que veo cómo te emocionas.",
        "Verte tan animada me hace querer hacer todo lo posible para mantener esa sonrisa en tu rostro.",
        "Tu emoción es contagiosa, y me alegra ser parte de tus momentos felices y animados.",
        "Me encanta cómo tu entusiasmo hace que cada experiencia sea aún más especial y memorable.",
        "Tu energía positiva es una de las razones por las que me enamoré de ti, y me encanta compartir tu emoción.",
        "Cada vez que te veo emocionada, me siento aún más afortunado de tenerte en mi vida.",
        "Tu pasión por la vida hace que cada día sea una aventura emocionante, y me encanta vivirla contigo.",
        "Tu alegría ilumina mi vida, y ver cómo te emocionas hace que todo sea más hermoso.",
        "Eres una persona increíblemente apasionada, y tu emoción es una de las cosas que más valoro de ti.",
        "Tu entusiasmo hace que cada momento sea más vibrante y significativo, y estoy agradecido por ello.",
        "Me haces sentir tan feliz y emocionado al verte tan animada y llena de energía.",
        "Tu alegría y emoción son un recordatorio constante de lo maravilloso que es estar a tu lado.",
        "Cada vez que veo tu entusiasmo, me siento inspirado a vivir la vida con la misma pasión que tú.",
        "Tu emoción y alegría hacen que cada día sea una celebración, y estoy agradecido por cada momento contigo.",

    ],
    tranquila: [
        "Me encanta ver cómo te relajas; tu tranquilidad es realmente contagiosa.",
        "Tu calma es un bálsamo para mi alma. Estoy tan feliz de estar a tu lado en estos momentos.",
        "Verte tranquila me recuerda lo hermoso que es simplemente estar juntos.",
        "Cuando estás tranquila, todo a tu alrededor parece perfecto. Gracias por compartir tu serenidad conmigo.",
        "Tu paz es como un refugio en medio del caos. Me alegra ser parte de tu calma.",
        "Cada vez que te veo en paz, me siento más cercano a ti y más agradecido por nuestro amor.",
        "Tu tranquilidad ilumina mi día de una manera especial. Me encanta estar contigo en estos momentos.",
        "Eres como un mar en calma, y tu serenidad me hace sentir en casa.",
        "Tu calma es un regalo, y me siento afortunado de disfrutar de este momento de paz contigo.",
        "Verte tan tranquila me hace sentir que todo está bien en el mundo. Gracias por ser mi ancla.",
        "Tu presencia serena hace que cualquier preocupación se desvanezca. Estoy aquí para disfrutar de tu tranquilidad.",
        "Me encanta cómo tu paz interior se refleja en tu sonrisa. Es un verdadero placer estar contigo.",
        "Tu tranquilidad es una melodía suave que hace que todo sea más hermoso. Estoy tan feliz de compartirlo contigo.",
        "Eres mi lugar de calma en medio de cualquier tormenta. Me alegra ver cómo encuentras tu paz.",
        "Cuando estás tranquila, me siento inspirado a disfrutar de cada momento a tu lado con la misma serenidad.",
        "Tu calma es un recordatorio de que lo más importante es disfrutar del presente. Gracias por estar aquí conmigo.",
        "Verte en paz me llena de una profunda felicidad. Estoy agradecido por cada instante de tranquilidad que compartimos.",
        "Tu serenidad es como una brisa suave que hace que todo se sienta más ligero. Estoy aquí para disfrutar de este momento contigo.",
        "Me encanta cómo tu tranquilidad me envuelve y me hace sentir en armonía contigo y con el mundo.",
        "Tu calma es la mejor compañía en un día agitado. Estoy feliz de estar a tu lado en estos momentos de serenidad.",
        "Cada momento que compartimos en paz es un tesoro, y me siento afortunado de tenerte en mi vida.",
        "Tu tranquilidad me recuerda lo importante que es encontrar la paz en cada día. Gracias por ser una fuente de calma.",
        "Tu presencia serena es el equilibrio perfecto en mi vida. Me alegra disfrutar de tu tranquilidad.",
        "Verte tan tranquila hace que mi corazón se llene de gratitud y amor. Estoy feliz de estar a tu lado.",
        "Tu calma es como un suave abrazo que envuelve mi alma. Me siento en paz cuando estoy contigo.",
        "Cada instante de serenidad contigo es un regalo. Gracias por compartir tu tranquilidad conmigo.",
        "Tu tranquilidad es un faro de luz que ilumina mi día. Estoy agradecido por cada momento de calma que compartimos.",
        "Me encanta cómo tu paz interior hace que todo a tu alrededor sea más hermoso. Estoy feliz de ser parte de tu tranquilidad.",
        "Tu serenidad es un refugio en el que encuentro consuelo y alegría. Gracias por estar a mi lado en estos momentos.",
        "Verte en paz me hace sentir que todo está en su lugar. Estoy agradecido por la calma que compartimos.",
        "Tu tranquilidad me recuerda la belleza de los momentos simples. Estoy feliz de disfrutar de este tiempo contigo.",
        "Tu calma es una inspiración, y me alegra estar a tu lado en estos momentos de serenidad.",
        "Me encanta cómo tu presencia tranquila hace que todo se sienta más armonioso. Estoy agradecido por tu compañía.",
        "Tu serenidad es una melodía suave que me hace sentir en casa. Gracias por compartir tu paz conmigo.",
        "Cada momento de calma contigo es un tesoro. Estoy feliz de estar a tu lado y disfrutar de tu tranquilidad.",
        "Tu tranquilidad es un recordatorio de lo hermoso que es simplemente estar presente. Me siento afortunado de compartir esto contigo.",
        "Verte tan tranquila me llena de una profunda paz. Estoy feliz de disfrutar de estos momentos de calma contigo.",
        "Tu calma es como un abrazo suave que envuelve mi corazón. Gracias por estar aquí y compartir tu serenidad.",
        "Tu serenidad hace que todo a tu alrededor se sienta más ligero y hermoso. Estoy agradecido por cada instante contigo.",
        "Me encanta cómo tu tranquilidad crea un ambiente de paz y armonía. Estoy feliz de estar a tu lado en estos momentos.",
    ],
    hot: [
        "Mandame mensaje YA😉🤭 Estas aun estan en proceso... 🙈❤️‍🔥 "
    ],
    drogada_Borracha: [
        "Voy a cuidar de ti hasta que te sientas mejor. Tu bienestar es lo que más me importa.",
        "Parece que tu bebida decidió hacer una fiesta en tu sistema.",
        "Hoy has alcanzado el nivel experto en ser adorablemente borrachita.!",
        "YA TE VI QUE TE ESTAS DROGANDO...NOO NO TE ESCONDAS ¡LAS AUTORIDADES HAN SIDO ALERTADAS! 🚨👮‍♂️👮‍♀️",
        "¿Cuantas llevas mi amor? 🙀",
        "¿Estás en modo avión? Porque creo que tu piloto automático está activado.",
        "Toy agarrando señal carnal",
        "Estás en modo de ahorro de energía, y me temo que el sistema no está disponible para preguntas.",
        "Ultimada madre, me importa mente. que me lleven a la jefacía de politura de ciudad. 👮 porque yo, ni siquiera borrando acho,🍺 solamente tres tomesas me cervé.🥴 escuchando los cachetes con lunares. 🤠",
        "Ya estás en modo 'la Chona', ¡pero sin tener que bailar!",
        "¡Parece que le diste al tequila más vueltas que un trompo!",
        "¿Qué tal si nos damos un break del licor y vamos a por unas tortas para el susto?",
        "¡Cuidado con el suelo, que parece que te quiere abrazar!",
        "No te preocupes, si te caes, al menos te levantas con estilo.",     
    ]
};

function mostrarFrase(emocion) {
    const frasesEmocion = frases[emocion];
    const fraseAleatoria = frasesEmocion[Math.floor(Math.random() * frasesEmocion.length)];
    document.getElementById('frase').textContent = fraseAleatoria;
    document.getElementById('emotion-header').textContent = emocion.charAt(0).toUpperCase() + emocion.slice(1);
    document.getElementById('header-text').style.display = 'none';
    document.getElementById('frase-container').style.display = 'block';
    document.querySelector('.buttons').style.display = 'none';
}

function volver() {
    document.getElementById('frase-container').style.display = 'none';
    document.querySelector('.buttons').style.display = 'block';
    document.getElementById('header-text').style.display = 'block';
}
